from tkinter import *
top=Tk()
top.geometry("1000x700")
top.title('CLASS')
top.config(bg='darkslategray')
welcome=Label(top,text='Welcome To Our Page', font=("cooper black",24,),bg='darkslategray',fg='white')
welcome.place(x=300,y=120)
def login():
    kit=Frame(top,bg="darkcyan",height=700,width=400)
    kit.pack(fill=X)
    detials=Label(kit,text='Login Page', font=("cooper black",26,),bg='darkcyan',fg='white')
    detials.place(x=400,y=100)
    user=Label(kit,text="Username",font=("TimesNewRoman",16,),bg='darkcyan',fg='white')
    user.place(x=510,y=360)
    password=Label(kit,text="Password",font=("TimesNewRoman",16,),bg='darkcyan',fg='white')
    password.place(x=510,y=410)
    entry=Entry(top,text="*",font=("TimesNewRoman",16,'italic'),bg='white')
    entry.place(x=650,y=360)
    entry2=Entry(top,show='*',font=("TimesNewRoman",16,'italic'),bg='white')
    entry2.place(x=650,y=410)
    button2=Button(top,text="Login",font=("TimesNewRoman",16,'italic'),bg='sky blue',fg='white',activebackground="red",activeforeground='black')
    button2.place(x=580,y=480,height=30,width=180)
    txt=Label(kit,text="Don't have account?",font=("TimesNewRoman",16,),bg='darkcyan',fg='white')
    txt.place(x=440,y=550)
    button3=Button(top,text="Sign In",font=("TimesNewRoman",16,'italic'),bg='darkorange',fg='white',activebackground="red",activeforeground='black')
    button3.place(x=680,y=550,height=30,width=180)
button1=Button(top,text="Get start",font=("TimesNewRoman",16,'italic'),bg='white',fg='black',activebackground="red",activeforeground='black',command=login)
button1.place(x=390,y=380,height=60,width=180)
top.mainloop()
